name: Check lint

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17  
          
      - name: Run ktlint
        uses: ScaCap/action-ktlint@v1.8.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          
          
    
