name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code    # 코드를 CI 서버에 체크아웃(푸쉬)
        uses: actions/checkout@v4

      - name: Run Lint             # Lint 실행
        run: ./gradlew lintDebug
        
      - name: Upload html test report
        uses: actions/upload-artifact@v3    # CI 서버에 업로드되어 다운로드 가능한 상태로 변경
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

        

