name: Firebase_App_Distribution_CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code    
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
          
      - name: Build Release with Gradle            
        run: |
            cd MyApp
            chmod +x ./gradlew    
            ./gradlew assembleRelease   

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: tester
            file: MyApp/app/build/outputs/apk/release/app-release-unsigned.apk
    
  
