name: Pull_Request_CI

on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code    # 코드를 CI 서버에 체크아웃(푸쉬)
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17  

      - name: Run ktlint             # Lint 실행
        run: |
            cd MyApp
            chmod +x ./gradlew    
            ./gradlew ktlintCheck
        

